package com.mirmedialabs.app;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.ColorFilter;
import android.graphics.Paint;
import android.graphics.Path;
import android.graphics.PixelFormat;
import android.graphics.drawable.Drawable;
import android.os.Build;
import android.text.SpannableStringBuilder;
import android.text.Spanned;
import android.text.style.DynamicDrawableSpan;
import android.text.style.ImageSpan;
import android.widget.TextView;

import java.util.HashMap;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/** MIR ICONS — generated by C:\\AiMir-Tools\\MirIcons\\build_icons.py from icons.py. DO NOT EDIT BY HAND.
 *  The one icon system for MirOS + Mir Media Labs (same 24x24 line icons as the web /static/icons/miros-icons.js).
 *  In any text: write [[name]] (e.g. "[[attach]] ATTACH") — Ui text helpers and Icons.set() turn it into the icon. */
public final class Icons {
    static final Map<String, String[]> D = new HashMap<>();
    static {
        D.put("close", new String[]{"p:M6 6L18 18", "p:M18 6L6 18"});
        D.put("plus", new String[]{"p:M12 5V19", "p:M5 12H19"});
        D.put("check", new String[]{"p:M5 12.5L10 17.5L19 7"});
        D.put("check-circle", new String[]{"c:12,12,9", "p:M8 12.5L11 15.5L16.5 9.5"});
        D.put("x-circle", new String[]{"c:12,12,9", "p:M9 9L15 15", "p:M15 9L9 15"});
        D.put("warn", new String[]{"p:M12 3.5L21.5 20H2.5Z", "p:M12 10V14", "f:12,17,1"});
        D.put("attach", new String[]{"p:M16.5 7.5L9 15C8 16 8 17.5 9 18.5C10 19.5 11.5 19.5 12.5 18.5L19.5 11.5C21.5 9.5 21.5 6.5 19.5 4.5C17.5 2.5 14.5 2.5 12.5 4.5L5 12C2.5 14.5 2.5 18.5 5 21"});
        D.put("gear", new String[]{"c:12,12,3", "c:12,12,6.5", "p:M12 2.5V5.5", "p:M12 18.5V21.5", "p:M2.5 12H5.5", "p:M18.5 12H21.5", "p:M5.3 5.3L7.4 7.4", "p:M16.6 16.6L18.7 18.7", "p:M5.3 18.7L7.4 16.6", "p:M16.6 7.4L18.7 5.3"});
        D.put("sliders", new String[]{"p:M4 7H14", "p:M18 7H20", "p:M4 17H8", "p:M12 17H20", "c:16,7,2", "c:10,17,2"});
        D.put("eject", new String[]{"p:M12 5L19 13H5Z", "p:M5 17.5H19"});
        D.put("power", new String[]{"p:M12 3V11", "p:M7 6.5C4.6 8.4 3.6 11.8 5 14.8C6.4 17.9 9 19.5 12 19.5C15 19.5 17.6 17.9 19 14.8C20.4 11.8 19.4 8.4 17 6.5"});
        D.put("play", new String[]{"p:M8 5L19 12L8 19Z"});
        D.put("pause", new String[]{"p:M9 5V19", "p:M15 5V19"});
        D.put("stop", new String[]{"p:M6 6H18V18H6Z"});
        D.put("rewind", new String[]{"p:M11 6L4 12L11 18Z", "p:M20 6L13 12L20 18Z"});
        D.put("forward", new String[]{"p:M13 6L20 12L13 18Z", "p:M4 6L11 12L4 18Z"});
        D.put("send", new String[]{"p:M4 12L20 4L14 20L11.5 13Z", "p:M11.5 13L20 4"});
        D.put("download", new String[]{"p:M12 4V15", "p:M7 10L12 15L17 10", "p:M5 20H19"});
        D.put("upload", new String[]{"p:M12 20V9", "p:M7 14L12 9L17 14", "p:M5 4H19"});
        D.put("trash", new String[]{"p:M4 7H20", "p:M9 7V4.5H15V7", "p:M6 7L7 20H17L18 7", "p:M10 11V16", "p:M14 11V16"});
        D.put("refresh", new String[]{"p:M20 12C20 16.4 16.4 20 12 20C7.6 20 4 16.4 4 12C4 7.6 7.6 4 12 4C14.8 4 17.2 5.4 18.6 7.6", "p:M19 3V8H14"});
        D.put("expand", new String[]{"p:M14 4H20V10", "p:M20 4L13 11", "p:M10 20H4V14", "p:M4 20L11 13"});
        D.put("external", new String[]{"p:M7 17L17 7", "p:M9 7H17V15"});
        D.put("arrow-right", new String[]{"p:M4 12H19", "p:M13 6L19 12L13 18"});
        D.put("arrow-left", new String[]{"p:M20 12H5", "p:M11 6L5 12L11 18"});
        D.put("chevron-down", new String[]{"p:M6 9L12 15L18 9"});
        D.put("chevron-right", new String[]{"p:M9 6L15 12L9 18"});
        D.put("chevron-left", new String[]{"p:M15 6L9 12L15 18"});
        D.put("search", new String[]{"c:11,11,6.5", "p:M16 16L20.5 20.5"});
        D.put("copy", new String[]{"p:M8 8H20V20H8Z", "p:M16 8V4H4V16H8"});
        D.put("pin", new String[]{"p:M6 11H18V21H6Z", "p:M8.5 11V7.5C8.5 5.5 10 4 12 4C14 4 15.5 5.5 15.5 7.5V11"});
        D.put("fingerprint", new String[]{"p:M7 10C7 7.2 9.2 5 12 5C14.8 5 17 7.2 17 10V12", "p:M10 21C10.5 18 10 15 10 12C10 10.9 10.9 10 12 10C13.1 10 14 10.9 14 12C14 15 14.4 17.4 15 19", "p:M4.5 15C4.5 13 4.5 11 4.8 9.6", "p:M19.3 16C19.5 14.5 19.5 13.5 19.5 12"});
        D.put("dot", new String[]{"f:12,12,5"});
        D.put("live", new String[]{"f:12,12,4", "c:12,12,8"});
        D.put("hourglass", new String[]{"p:M7 3H17", "p:M7 21H17", "p:M8 3C8 8 16 8 16 12C16 16 8 16 8 21", "p:M16 3C16 8 8 8 8 12C8 16 16 16 16 21"});
        D.put("clock", new String[]{"c:12,12,9", "p:M12 7V12L15.5 14"});
        D.put("bell", new String[]{"p:M6 16V11C6 7.7 8.7 5 12 5C15.3 5 18 7.7 18 11V16L19.5 18H4.5Z", "p:M10 20.5C10.4 21.3 11.1 21.7 12 21.7C12.9 21.7 13.6 21.3 14 20.5"});
        D.put("shield", new String[]{"p:M12 3L19.5 6V11.5C19.5 16 16.5 19.5 12 21C7.5 19.5 4.5 16 4.5 11.5V6Z", "p:M9 12L11 14L15 10"});
        D.put("lock", new String[]{"p:M6 11H18V21H6Z", "p:M8.5 11V7.5C8.5 5.5 10 4 12 4C14 4 15.5 5.5 15.5 7.5V11", "f:12,16,1.2"});
        D.put("key", new String[]{"c:8,15,4", "p:M11 12L20 3", "p:M17 6L20 9", "p:M15 8L17 10"});
        D.put("sun", new String[]{"c:12,12,4", "p:M12 2.5V4.5", "p:M12 19.5V21.5", "p:M2.5 12H4.5", "p:M19.5 12H21.5", "p:M5.3 5.3L6.7 6.7", "p:M17.3 17.3L18.7 18.7", "p:M5.3 18.7L6.7 17.3", "p:M17.3 6.7L18.7 5.3"});
        D.put("cloud", new String[]{"p:M7 18H17C19.5 18 21 16.2 21 14C21 11.8 19.3 10.2 17.2 10.3C16.6 7.8 14.5 6 12 6C9 6 6.8 8.3 6.8 11.2C4.7 11.5 3 13 3 15C3 16.7 4.6 18 7 18Z"});
        D.put("core", new String[]{"c:12,12,9", "c:12,12,4.5", "f:12,12,1.6"});
        D.put("grid", new String[]{"p:M4 4H10V10H4Z", "p:M14 4H20V10H14Z", "p:M4 14H10V20H4Z", "p:M14 14H20V20H14Z"});
        D.put("finance", new String[]{"p:M3 3V21H21", "p:M7 15L11 10L14 13L20 6", "p:M16 6H20V10"});
        D.put("dollar", new String[]{"p:M12 3V21", "p:M16.5 7C16 5.8 14.3 5 12 5C9.2 5 7.5 6.3 7.5 8.2C7.5 12.4 16.5 10.6 16.5 15.4C16.5 17.4 14.6 19 12 19C9.4 19 7.7 18 7.2 16.6"});
        D.put("command", new String[]{"p:M9 9H15V15H9Z", "c:6.5,6.5,2.5", "c:17.5,6.5,2.5", "c:6.5,17.5,2.5", "c:17.5,17.5,2.5"});
        D.put("lab", new String[]{"p:M9 3H15", "p:M10 3V9L4.5 18.5C4 19.6 4.7 21 6 21H18C19.3 21 20 19.6 19.5 18.5L14 9V3", "p:M7 15H17"});
        D.put("mail", new String[]{"p:M3 6H21V18H3Z", "p:M3 7L12 13L21 7"});
        D.put("server", new String[]{"p:M4 4H20V10H4Z", "p:M4 14H20V20H4Z", "f:7.5,7,1", "f:7.5,17,1"});
        D.put("users", new String[]{"c:9,8,3.2", "p:M3.5 19C3.5 15.5 6 13.5 9 13.5C12 13.5 14.5 15.5 14.5 19", "c:16.5,9,2.5", "p:M16 13.6C18.8 13.6 20.5 15.5 20.5 18.5"});
        D.put("user", new String[]{"c:12,8,4", "p:M4.5 20C4.5 16 8 13.5 12 13.5C16 13.5 19.5 16 19.5 20"});
        D.put("cpu", new String[]{"p:M7 7H17V17H7Z", "p:M10 10H14V14H10Z", "p:M9 3V7", "p:M15 3V7", "p:M9 17V21", "p:M15 17V21", "p:M3 9H7", "p:M3 15H7", "p:M17 9H21", "p:M17 15H21"});
        D.put("vault", new String[]{"p:M4 5H20V19H4Z", "c:12,12,3.5", "p:M12 8.5V6.5", "p:M7 19V21", "p:M17 19V21"});
        D.put("radar", new String[]{"c:12,12,9", "c:12,12,5", "p:M12 12L18.5 5.5", "f:12,12,1.4"});
        D.put("agent", new String[]{"F:M12 4L20 12L12 20L4 12Z"});
        D.put("diamond", new String[]{"p:M12 3L21 12L12 21L3 12Z", "p:M12 8L16 12L12 16L8 12Z"});
        D.put("bolt", new String[]{"p:M13 2L4 14H11L10 22L20 9H13Z"});
        D.put("book", new String[]{"p:M12 6C10 4.5 7 4 4 4.5V19C7 18.5 10 19 12 20.5C14 19 17 18.5 20 19V4.5C17 4 14 4.5 12 6Z", "p:M12 6V20.5"});
        D.put("chain", new String[]{"p:M10 14L14 10", "p:M8.5 11.5L6.5 13.5C5 15 5 17.5 6.5 19C8 20.5 10.5 20.5 12 19L14 17", "p:M15.5 12.5L17.5 10.5C19 9 19 6.5 17.5 5C16 3.5 13.5 3.5 12 5L10 7"});
        D.put("brain", new String[]{"p:M12 5C10.5 3.5 7 4 6.8 7C4.5 7.4 3.6 10.4 5.2 12.2C4 14.5 5.6 17.6 8.4 17.4C9.4 19.6 12 19.6 12 18.5Z", "p:M12 5C13.5 3.5 17 4 17.2 7C19.5 7.4 20.4 10.4 18.8 12.2C20 14.5 18.4 17.6 15.6 17.4C14.6 19.6 12 19.6 12 18.5"});
        D.put("keyboard", new String[]{"p:M3 7H21V17H3Z", "p:M7 14H17", "p:M6 10.5H7", "p:M9.5 10.5H10.5", "p:M13.5 10.5H14.5", "p:M17 10.5H18"});
        D.put("type", new String[]{"p:M4 19L9 5L14 19", "p:M6 14H12", "p:M21 19V12.5C21 11 20 10 18.8 10C17.6 10 16.9 10.6 16.6 11.4", "p:M21 14.6C18.6 14.6 16.6 15.2 16.6 17C16.6 18.4 17.6 19.1 18.8 19.1C20 19.1 21 18.2 21 17"});
        D.put("mute", new String[]{"p:M4 9H8L13 5V19L8 15H4Z", "p:M16.5 9.5L21 14.5", "p:M21 9.5L16.5 14.5"});
        D.put("volume", new String[]{"p:M4 9H8L13 5V19L8 15H4Z", "p:M16 9C17.5 10.5 17.5 13.5 16 15", "p:M18.5 6.5C21.5 9.5 21.5 14.5 18.5 17.5"});
        D.put("music", new String[]{"p:M9 18V6L19 4V16", "c:7,18,2", "c:17,16,2"});
        D.put("mic", new String[]{"p:M9 4.5C9 3.4 10.2 2.5 12 2.5C13.8 2.5 15 3.4 15 4.5V12C15 13.5 13.8 14.5 12 14.5C10.2 14.5 9 13.5 9 12Z", "p:M5.5 11C5.5 15 8.4 17.5 12 17.5C15.6 17.5 18.5 15 18.5 11", "p:M12 17.5V21"});
        D.put("image", new String[]{"p:M3 5H21V19H3Z", "c:8.5,9.5,1.8", "p:M3 17L9 12L13 15.5L16 13L21 17"});
        D.put("video", new String[]{"p:M3 6H16V18H3Z", "p:M16 10.5L21 7.5V16.5L16 13.5"});
        D.put("film", new String[]{"p:M4 4H20V20H4Z", "p:M8 4V20", "p:M16 4V20", "p:M4 8H8", "p:M4 12H8", "p:M4 16H8", "p:M16 8H20", "p:M16 12H20", "p:M16 16H20"});
        D.put("disc", new String[]{"c:12,12,9", "c:12,12,2.5", "p:M12 5.5C8.4 5.5 5.5 8.4 5.5 12"});
        D.put("drum", new String[]{"p:M4 8C4 6.3 7.6 5 12 5C16.4 5 20 6.3 20 8C20 9.7 16.4 11 12 11C7.6 11 4 9.7 4 8Z", "p:M4 8V16C4 17.7 7.6 19 12 19C16.4 19 20 17.7 20 16V8", "p:M9 11V19", "p:M15 11V19"});
        D.put("palette", new String[]{"p:M12 3C7 3 3 6.8 3 11.5C3 16.2 6.8 20 11.5 20C13 20 13.5 19 13 17.8C12.4 16.4 13.3 15 15 15H17C19.3 15 21 13.2 21 11C21 6.6 17 3 12 3Z", "f:7.5,11,1.1", "f:10,7,1.1", "f:15,7,1.1"});
        D.put("wand", new String[]{"p:M4 20L15 9", "p:M13.5 7.5L16.5 10.5", "p:M18 3V6", "p:M16.5 4.5H19.5", "p:M20 9V11", "p:M19 10H21", "p:M10 3V5", "p:M9 4H11"});
        D.put("sparkle", new String[]{"p:M12 3C12.6 8.4 15.6 11.4 21 12C15.6 12.6 12.6 15.6 12 21C11.4 15.6 8.4 12.6 3 12C8.4 11.4 11.4 8.4 12 3Z"});
        D.put("star", new String[]{"p:M12 3L14.6 8.6L20.7 9.3L16.2 13.5L17.4 19.6L12 16.6L6.6 19.6L7.8 13.5L3.3 9.3L9.4 8.6Z"});
        D.put("scissors", new String[]{"c:6,7,2.5", "c:6,17,2.5", "p:M8.2 8.3L20 18", "p:M8.2 15.7L20 6"});
        D.put("box", new String[]{"p:M12 3L20.5 7.5V16.5L12 21L3.5 16.5V7.5Z", "p:M3.5 7.5L12 12L20.5 7.5", "p:M12 12V21"});
        D.put("phone", new String[]{"p:M7 2.5H17V21.5H7Z", "p:M11 18.5H13"});
        D.put("coffee", new String[]{"p:M5 9H16V15C16 17.8 13.8 20 11 20H10C7.2 20 5 17.8 5 15Z", "p:M16 11H18C19.4 11 20 12 20 13C20 14.4 19 15 18 15H16", "p:M8 3V6", "p:M11 3V6"});
        D.put("note", new String[]{"p:M6 3H14L19 8V21H6Z", "p:M14 3V8H19", "p:M9 13H16", "p:M9 17H14"});
        D.put("folder", new String[]{"p:M3 6C3 5 4 4.5 4.8 4.5H9.5L11.5 7H19.2C20.2 7 21 7.8 21 8.8V18C21 19 20.2 19.5 19.2 19.5H4.8C3.8 19.5 3 19 3 18Z"});
        D.put("layers", new String[]{"p:M12 3L21 8L12 13L3 8Z", "p:M3 12L12 17L21 12", "p:M3 16L12 21L21 16"});
        D.put("bug", new String[]{"p:M8 10C8 7.8 9.8 6 12 6C14.2 6 16 7.8 16 10V15C16 17.8 14.2 20 12 20C9.8 20 8 17.8 8 15Z", "p:M12 10V20", "p:M9.5 4.5L10.5 6", "p:M14.5 4.5L13.5 6", "p:M4 12H8", "p:M16 12H20", "p:M4.5 18L8.3 16.5", "p:M19.5 18L15.7 16.5"});
        D.put("heart", new String[]{"p:M12 20C12 20 3.5 14.8 3.5 9.2C3.5 6.6 5.5 4.5 8 4.5C9.7 4.5 11.2 5.4 12 6.8C12.8 5.4 14.3 4.5 16 4.5C18.5 4.5 20.5 6.6 20.5 9.2C20.5 14.8 12 20 12 20Z"});
        D.put("code", new String[]{"p:M8 7L3 12L8 17", "p:M16 7L21 12L16 17", "p:M14 4L10 20"});
        D.put("qr", new String[]{"p:M4 4H10V10H4Z", "p:M14 4H20V10H14Z", "p:M4 14H10V20H4Z", "f:7,7,1", "f:17,7,1", "f:7,17,1", "p:M14 14H16.5V16.5", "p:M20 14V17", "p:M17 20H20", "p:M14 18.5V20"});
        D.put("scan", new String[]{"p:M4 9V5.5C4 4.7 4.7 4 5.5 4H9", "p:M15 4H18.5C19.3 4 20 4.7 20 5.5V9", "p:M20 15V18.5C20 19.3 19.3 20 18.5 20H15", "p:M9 20H5.5C4.7 20 4 19.3 4 18.5V15", "p:M7 12H17"});
        D.put("link", new String[]{"p:M10 14C11.2 15.2 13 15.2 14.2 14L17.5 10.7C18.7 9.5 18.7 7.6 17.5 6.5C16.3 5.3 14.5 5.3 13.3 6.5L12.5 7.3", "p:M14 10C12.8 8.8 11 8.8 9.8 10L6.5 13.3C5.3 14.5 5.3 16.4 6.5 17.5C7.7 18.7 9.5 18.7 10.7 17.5L11.5 16.7"});
        D.put("wifi", new String[]{"p:M3 9.5C8 5 16 5 21 9.5", "p:M6 12.8C9.4 9.9 14.6 9.9 18 12.8", "p:M9 16C10.7 14.6 13.3 14.6 15 16", "f:12,19,1.2"});
        D.put("globe", new String[]{"c:12,12,9", "p:M3 12H21", "p:M12 3C9.5 5.5 8.5 8.5 8.5 12C8.5 15.5 9.5 18.5 12 21", "p:M12 3C14.5 5.5 15.5 8.5 15.5 12C15.5 15.5 14.5 18.5 12 21"});
        D.put("router", new String[]{"p:M3 13H21V19H3Z", "p:M7 13V7", "p:M17 13V7", "p:M5 5.5C6 4.5 8 4.5 9 5.5", "p:M15 5.5C16 4.5 18 4.5 19 5.5", "f:7,16,1", "f:10.5,16,1", "p:M14 16H18"});
        D.put("camera", new String[]{"p:M4 8H7.5L9 5.5H15L16.5 8H20V19H4Z", "c:12,13,3.5"});
        D.put("clipboard", new String[]{"p:M8 4.5H6V21H18V4.5H16", "p:M9 3H15V6H9Z", "p:M9 11H15", "p:M9 15H13"});
        D.put("tv", new String[]{"p:M3 7H21V18H3Z", "p:M8 3L12 7L16 3", "p:M8 21H16"});
        D.put("cc", new String[]{"p:M3 6H21V18H3Z", "p:M10.5 10C9.8 9.4 8.9 9.2 8.2 9.6C7.2 10.1 7 11.4 7.2 12.3C7.5 13.6 9 14.4 10.5 13.8", "p:M17 10C16.3 9.4 15.4 9.2 14.7 9.6C13.7 10.1 13.5 11.4 13.7 12.3C14 13.6 15.5 14.4 17 13.8"});
        D.put("pip", new String[]{"p:M3 5H21V19H3Z", "p:M12 12H19V17H12Z"});
        D.put("compass", new String[]{"c:12,12,9", "p:M15.5 8.5L13.5 13.5L8.5 15.5L10.5 10.5Z"});
    }
    private static final Pattern TOKEN = Pattern.compile("\\[\\[([a-zA-Z0-9-]+)\\]\\]");

    /** Line-icon drawable in one colour. */
    public static final class Icon extends Drawable {
        final String[] els; int color;
        private final Paint p = new Paint(Paint.ANTI_ALIAS_FLAG);
        public Icon(String name, int color) { els = D.containsKey(name) ? D.get(name) : new String[0]; this.color = color; }
        public void setColor(int c) { color = c; invalidateSelf(); }
        @Override public void draw(Canvas c) {
            android.graphics.Rect b = getBounds();
            float s = Math.min(b.width(), b.height()) / 24f;
            c.save();
            c.translate(b.left + (b.width() - 24 * s) / 2, b.top + (b.height() - 24 * s) / 2);
            c.scale(s, s);
            p.setColor(color);
            p.setStrokeCap(Paint.Cap.ROUND); p.setStrokeJoin(Paint.Join.ROUND); p.setStrokeWidth(1.8f);
            for (String e : els) {
                char k = e.charAt(0); String d = e.substring(2);
                if (k == 'p' || k == 'F') { p.setStyle(k == 'F' ? Paint.Style.FILL : Paint.Style.STROKE); c.drawPath(parse(d), p); }
                else { String[] n = d.split(","); p.setStyle(k == 'f' ? Paint.Style.FILL : Paint.Style.STROKE);
                    c.drawCircle(Float.parseFloat(n[0]), Float.parseFloat(n[1]), Float.parseFloat(n[2]), p); }
            }
            c.restore();
        }
        @Override public void setAlpha(int a) { p.setAlpha(a); }
        @Override public void setColorFilter(ColorFilter f) { p.setColorFilter(f); }
        @Override public int getOpacity() { return PixelFormat.TRANSLUCENT; }
    }

    public static Icon drawable(String name, int color, int sizePx) { Icon i = new Icon(name, color); i.setBounds(0, 0, sizePx, sizePx); return i; }

    /** [[name]] tokens → inline icons sized to the text. */
    public static CharSequence apply(CharSequence s, float textPx, int color) {
        if (s == null) return "";
        String str = s.toString();
        if (!str.contains("[[")) return s;
        SpannableStringBuilder b = new SpannableStringBuilder();
        Matcher m = TOKEN.matcher(str);
        int last = 0;
        while (m.find()) {
            b.append(str, last, m.start());
            int at = b.length();
            b.append("\uFFFC");
            Icon ic = drawable(m.group(1).toLowerCase(java.util.Locale.US), color, Math.round(textPx * 1.15f));
            int align = Build.VERSION.SDK_INT >= 29 ? DynamicDrawableSpan.ALIGN_CENTER : DynamicDrawableSpan.ALIGN_BASELINE;
            b.setSpan(new ImageSpan(ic, align), at, at + 1, Spanned.SPAN_EXCLUSIVE_EXCLUSIVE);
            last = m.end();
        }
        b.append(str, last, str.length());
        return b;
    }
    public static void set(TextView t, CharSequence s) { t.setText(apply(s, t.getTextSize(), t.getCurrentTextColor())); }
    /** After a colour change (pills): recolour the inline icons too. */
    public static void tint(TextView t) {
        CharSequence cs = t.getText();
        if (!(cs instanceof Spanned)) return;
        for (ImageSpan sp : ((Spanned) cs).getSpans(0, cs.length(), ImageSpan.class))
            if (sp.getDrawable() instanceof Icon) ((Icon) sp.getDrawable()).setColor(t.getCurrentTextColor());
        t.invalidate();
    }
    /** Plain-text fallback (toasts / notifications / dialogs): drop the tokens. */
    public static String plain(String s) { return s == null ? "" : TOKEN.matcher(s).replaceAll("").replaceAll("  +", " ").trim(); }

    // ── tiny SVG path parser: M L H V C Q Z (absolute + relative) ──
    private static final Map<String, Path> CACHE = new HashMap<>();
    static Path parse(String d) {
        Path cached = CACHE.get(d);
        if (cached != null) return cached;
        Path p = new Path();
        Matcher m = Pattern.compile("([MLHVCQZmlhvcqz])|(-?\\d*\\.?\\d+(?:e-?\\d+)?)").matcher(d);
        java.util.List<Object> tok = new java.util.ArrayList<>();
        while (m.find()) tok.add(m.group(1) != null ? (Object) m.group(1).charAt(0) : (Object) Float.parseFloat(m.group(2)));
        float x = 0, y = 0, sx = 0, sy = 0; char cmd = 'M'; int i = 0;
        while (i < tok.size()) {
            if (tok.get(i) instanceof Character) { cmd = (Character) tok.get(i); i++; if (cmd == 'Z' || cmd == 'z') { p.close(); x = sx; y = sy; continue; } }
            boolean rel = Character.isLowerCase(cmd);
            float ox = rel ? x : 0, oy = rel ? y : 0;
            switch (Character.toUpperCase(cmd)) {
                case 'M': x = ox + (Float) tok.get(i); y = oy + (Float) tok.get(i + 1); i += 2; p.moveTo(x, y); sx = x; sy = y; cmd = rel ? 'l' : 'L'; break;
                case 'L': x = ox + (Float) tok.get(i); y = oy + (Float) tok.get(i + 1); i += 2; p.lineTo(x, y); break;
                case 'H': x = ox + (Float) tok.get(i); i += 1; p.lineTo(x, y); break;
                case 'V': y = oy + (Float) tok.get(i); i += 1; p.lineTo(x, y); break;
                case 'C': { float a = ox + (Float) tok.get(i), b2 = oy + (Float) tok.get(i + 1), c2 = ox + (Float) tok.get(i + 2), d2 = oy + (Float) tok.get(i + 3);
                    x = ox + (Float) tok.get(i + 4); y = oy + (Float) tok.get(i + 5); i += 6; p.cubicTo(a, b2, c2, d2, x, y); break; }
                case 'Q': { float a = ox + (Float) tok.get(i), b2 = oy + (Float) tok.get(i + 1);
                    x = ox + (Float) tok.get(i + 2); y = oy + (Float) tok.get(i + 3); i += 4; p.quadTo(a, b2, x, y); break; }
                default: i++;
            }
        }
        CACHE.put(d, p);
        return p;
    }
}
