"""Plain-language docs for every ⚙ setting — merged into params.schema() so the web UI and the app show a
simple name, the technical term (small), a one-line "what it does", and preview media where it exists.

Keys (k) and option values never change here — saved prefs and --flags keep working. Old apps simply
ignore the extra keys. Previews are generated by tools/make_param_previews.py into static/fx/ and listed
in static/fx/manifest.json; an option only gets a preview once its file exists.

Field doc:  {"label", "tech", "desc", "advanced", "opts": {value: {"label", "tech", "desc"}}}
"""
import json
import os

FX_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "static", "fx")

# ── shared by every model (a model's own entry wins) ──
COMMON = {
    "seed": {"label": "Variation number", "tech": "seed", "advanced": True,
             "desc": "Same number + same settings = the same result. Blank picks a new one each time."},
    "steps": {"label": "Detail passes", "tech": "steps", "advanced": True,
              "desc": "How many refining passes. More is slower and only sometimes better."},
    "cfg": {"label": "Prompt strictness", "tech": "CFG", "advanced": True,
            "desc": "How tightly it follows your words. Too high looks harsh or over-coloured."},
    "sampler": {"label": "Render method", "tech": "sampler", "advanced": True,
                "desc": "The maths that turns noise into the result. Keep the default unless testing.",
                "opts": {"euler": {"desc": "Simple and reliable — the safe default."},
                         "euler_ancestral": {"desc": "Adds fresh randomness each pass — looser, more varied."},
                         "res_multistep": {"desc": "Tuned for MiniMax H3 — best default for video."},
                         "dpmpp_2m": {"desc": "Sharp and detailed; a classic for SDXL-style models."},
                         "dpmpp_2m_sde": {"desc": "Like dpmpp_2m with a little randomness — softer, organic."},
                         "dpmpp_sde": {"desc": "Detailed but slow."},
                         "er_sde": {"desc": "Smooth, stable motion; slightly slower."},
                         "uni_pc": {"desc": "Good results in few passes."},
                         "heun": {"desc": "Accurate but twice as slow."},
                         "lcm": {"desc": "Only for fast-distilled (LCM) models."},
                         "deis": {"desc": "Efficient at low pass counts."}}},
    "scheduler": {"label": "Pass spacing", "tech": "scheduler", "advanced": True,
                  "desc": "How the passes are spread from rough to fine. Keep the default.",
                  "opts": {"auto": {"desc": "Picks the right one for the mode."},
                           "simple": {"desc": "Even spacing — the default for most models."},
                           "normal": {"desc": "Standard spacing."},
                           "karras": {"desc": "More passes on fine detail — crisp images."},
                           "exponential": {"desc": "Front-loads big changes."},
                           "sgm_uniform": {"desc": "For turbo / distilled models."},
                           "beta": {"desc": "Balanced; good for H3 reference mode at full quality."},
                           "linear_quadratic": {"desc": "Gentle start, faster finish."}}},
    "workflow": {"label": "Node graph", "tech": "ComfyUI workflow", "advanced": True,
                 "desc": "Use the built-in pipeline, or one you designed in ComfyUI."},
    "quality": {"label": "Audio file quality", "tech": "MP3 bitrate",
                "desc": "Higher sounds better and makes a bigger file.",
                "opts": {"V0": {"label": "Best", "tech": "V0 VBR"}, "320k": {"label": "High", "tech": "320 kbps"},
                         "128k": {"label": "Small file", "tech": "128 kbps"}}},
    "denoise": {"label": "Change amount", "tech": "denoise", "advanced": True,
                "desc": "1 = brand new. Lower keeps more of the starting picture or clip."},
}

DOCS = {
    "h3": {
        # basics
        "mode": {"label": "What to make from", "tech": "mode",
                 "desc": "Text only, a starting picture, start+end pictures, references, a storyboard, or extending a clip.",
                 "opts": {"auto": {"label": "Automatic", "desc": "Uses whatever you attached in the best way."},
                          "t2v": {"label": "From words", "tech": "text → video", "desc": "Just your description."},
                          "i2v": {"label": "Animate a picture", "tech": "image → video", "desc": "Your first picture becomes the opening frame."},
                          "flf2v": {"label": "Start + end picture", "tech": "first/last frame", "desc": "Moves from picture 1 to picture 2."},
                          "r2v": {"label": "Use references", "tech": "reference → video", "desc": "Keeps faces, products or style from your pictures."},
                          "story": {"label": "Storyboard", "desc": "Each picture is a moment the video passes through, in order."},
                          "extend": {"label": "Continue a clip", "desc": "Picks up where the attached video ends."},
                          "sing": {"label": "Sing to my audio", "tech": "audio-guided lip-sync",
                                   "desc": "The character's mouth follows the song or voice you attached. Attach a picture to start, or the previous clip to continue it."}}},
        "aspect": {"label": "Shape", "tech": "aspect ratio", "desc": "Wide for screens, tall for phones, square for feeds.",
                   "opts": {"auto": {"label": "Automatic", "desc": "Matches your picture, else wide 16:9."},
                            "16:9": {"label": "Wide 16:9", "desc": "TV, YouTube."}, "9:16": {"label": "Tall 9:16", "desc": "Reels, TikTok, Shorts."},
                            "1:1": {"label": "Square", "desc": "Feeds and profile posts."}, "4:3": {"label": "Classic 4:3"},
                            "3:4": {"label": "Portrait 3:4"}, "21:9": {"label": "Cinema wide 21:9", "desc": "Movie-style letterbox."}}},
        "res": {"label": "Sharpness / size", "tech": "resolution", "desc": "Bigger looks sharper but renders slower.",
                "opts": {"draft": {"label": "Quick draft", "desc": "Fast test to check the idea."},
                         "standard": {"label": "Standard", "desc": "Good balance of speed and detail."},
                         "high": {"label": "High", "desc": "Sharper, slower."},
                         "max": {"label": "Maximum 768p", "desc": "Sharpest; slowest and uses the most memory."}}},
        "seconds": {"label": "Clip length", "tech": "seconds", "desc": "Length of each clip, 4 to 15 seconds."},
        "quality": {"label": "Speed vs quality", "tech": "turbo LoRA / steps", "desc": "Turbo is fast; Full is slow but cleaner motion and sound.",
                    "opts": {"turbo4": {"label": "Fastest", "tech": "4-step turbo", "desc": "Quick previews."},
                             "turbo8": {"label": "Fast", "tech": "8-step turbo", "desc": "The everyday default."},
                             "full": {"label": "Best quality", "tech": "20 steps, no LoRA", "desc": "Several times slower."}}},
        "seed": {"advanced": False},
        # extend / storyboard
        "extend": {"label": "Make it longer", "tech": "extend clips",
                   "desc": "Adds more clips that continue from the last one, joined into one video."},
        "extend_anchor": {"label": "How smoothly clips connect", "tech": "continuity anchor",
                          "desc": "More carried-over frames = smoother hand-off between clips.",
                          "opts": {"22": {"label": "Smoothest", "tech": "last 22 frames"},
                                   "5": {"label": "Medium", "tech": "last 5 frames"},
                                   "1": {"label": "Loosest", "tech": "last frame only"}}},
        "extend_prompt": {"label": "What happens next", "desc": "One idea per extra clip, separated by ||."},
        "story_secs": {"label": "Time between storyboard pictures", "desc": "Seconds spent getting from one picture to the next."},
        "join": {"label": "How clips are joined", "desc": "A clean cut, or a quick dissolve.",
                 "opts": {"cut": {"label": "Seamless cut"}, "xfade": {"label": "Quick dissolve", "tech": "0.25 s crossfade"}}},
        # camera & motion
        "camera": {"label": "Camera movement", "tech": "camera move", "desc": "How the camera travels during the clip.",
                   "opts": {"auto": {"label": "Let MUSE pick", "desc": "Chooses a move that fits the scene."},
                            "static": {"label": "Still camera", "tech": "locked-off", "desc": "Camera doesn't move; only the scene does."},
                            "dolly_in": {"label": "Push in", "tech": "dolly-in", "desc": "Glides toward the subject — builds focus or tension."},
                            "dolly_out": {"label": "Pull back", "tech": "dolly-out reveal", "desc": "Backs away to reveal the surroundings."},
                            "orbit": {"label": "Circle around", "tech": "orbit", "desc": "Travels around the subject — a showcase move."},
                            "crane_up": {"label": "Rise up", "tech": "crane up", "desc": "Lifts upward, often revealing the wider scene."},
                            "crane_down": {"label": "Lower down", "tech": "crane down", "desc": "Descends from above toward the action."},
                            "tracking": {"label": "Follow alongside", "tech": "tracking shot", "desc": "Moves with the subject as it travels."},
                            "handheld": {"label": "Handheld", "desc": "Slight natural shake — feels real and personal."},
                            "pan_left": {"label": "Turn left", "tech": "pan left", "desc": "Camera swivels left from one spot."},
                            "pan_right": {"label": "Turn right", "tech": "pan right", "desc": "Camera swivels right from one spot."},
                            "tilt_up": {"label": "Look up", "tech": "tilt up", "desc": "Camera tips upward — great for tall things."},
                            "zoom_in": {"label": "Slow zoom", "tech": "zoom-in", "desc": "Lens zooms in without the camera moving."},
                            "fpv": {"label": "Drone fly-through", "tech": "FPV", "desc": "Fast, swooping flight through the scene."},
                            "aerial": {"label": "From the sky", "tech": "aerial establishing", "desc": "High overhead view of the place."},
                            "pov": {"label": "Through their eyes", "tech": "first-person POV", "desc": "We see what the character sees."}}},
        "shot": {"label": "How close", "tech": "shot size", "desc": "How much of the subject fills the frame.",
                 "opts": {"auto": {"label": "Automatic"},
                          "extreme_wide": {"label": "Very far", "tech": "extreme wide", "desc": "Tiny subject in a huge place."},
                          "wide": {"label": "Far", "tech": "wide", "desc": "Whole body plus surroundings."},
                          "medium": {"label": "Waist up", "tech": "medium", "desc": "Good for talking and gestures."},
                          "close": {"label": "Close", "tech": "close-up", "desc": "Face fills the frame — emotion."},
                          "extreme_close": {"label": "Very close", "tech": "extreme close-up", "desc": "Eyes, hands or a small detail."},
                          "low_angle": {"label": "From below", "tech": "low angle", "desc": "Looks up — subject feels powerful."},
                          "high_angle": {"label": "From above", "tech": "high angle", "desc": "Looks down — subject feels small."},
                          "overhead": {"label": "Straight down", "tech": "top-down", "desc": "Bird's-eye view."}}},
        "motion": {"label": "How much movement", "tech": "motion amount", "desc": "From calm and gentle to fast action.",
                   "opts": {"auto": {"label": "Automatic"}, "subtle": {"label": "Calm", "desc": "Small, gentle movement."},
                            "natural": {"label": "Natural", "desc": "Everyday real-life pace."},
                            "dynamic": {"label": "Energetic", "desc": "Lively, bigger movement."},
                            "extreme": {"label": "Action", "desc": "Fast, intense movement."}}},
        "steady": {"label": "Smooth camera", "tech": "stabilised", "desc": "On keeps the camera steady and smooth.",
                   "opts": {"on": {"label": "On"}, "off": {"label": "Off"}}},
        "speed": {"label": "Playback speed", "desc": "Slow motion or sped up — applied after rendering.",
                  "opts": {"0.5": {"label": "Half speed", "desc": "Dreamy slow motion."}, "0.75": {"label": "Slightly slow"},
                           "1": {"label": "Normal"}, "1.25": {"label": "Slightly fast"}, "1.5": {"label": "Fast"},
                           "2": {"label": "Double speed", "desc": "Rushed, comic or timelapse feel."}}},
        # scene & effects
        "look": {"label": "Visual style", "tech": "look", "desc": "The overall feel — film, phone video, anime, painting…",
                 "opts": {"auto": {"label": "Automatic"},
                          "cinematic": {"label": "Movie", "desc": "Rich colour and shallow focus, like a film."},
                          "photoreal": {"label": "Phone video", "desc": "Looks like real everyday footage."},
                          "documentary": {"label": "Documentary", "desc": "Natural, observational, unpolished."},
                          "commercial": {"label": "TV advert", "desc": "Glossy, bright and polished."},
                          "music_video": {"label": "Music video", "desc": "Bold colour and stylish framing."},
                          "anime": {"label": "Anime", "desc": "Japanese animation style."},
                          "3d": {"label": "3D cartoon", "desc": "Like an animated feature film."},
                          "claymation": {"label": "Clay animation", "desc": "Hand-made plasticine look."},
                          "noir": {"label": "Black & white noir", "desc": "Dramatic shadows, 1940s detective mood."},
                          "vintage": {"label": "Old film", "tech": "16 mm", "desc": "Warm, grainy home-movie film."},
                          "vhs": {"label": "90s camcorder", "tech": "VHS", "desc": "Fuzzy tape look with colour bleed."},
                          "cyberpunk": {"label": "Neon future", "tech": "cyberpunk", "desc": "Rainy night city, pink-blue neon."},
                          "watercolor": {"label": "Watercolour", "desc": "Soft painted look."}}},
        "scene_fx": {"label": "Weather & effects", "tech": "scene effect", "desc": "Adds something into the scene itself.",
                     "opts": {"none": {"label": "None"}, "rain": {"label": "Rain"}, "snow": {"label": "Snow"},
                              "fog": {"label": "Fog", "desc": "Soft mist that hides the distance."},
                              "smoke": {"label": "Smoke"}, "sparks": {"label": "Sparks & embers"},
                              "dust": {"label": "Dust in light", "desc": "Glowing beams with floating dust."},
                              "petals": {"label": "Falling petals"}, "confetti": {"label": "Confetti"},
                              "lightning": {"label": "Lightning storm"}, "particles": {"label": "Magic sparkles"},
                              "bubbles": {"label": "Bubbles"}, "underwater": {"label": "Underwater light", "desc": "Rippling light patterns."},
                              "explosion": {"label": "Explosion"}, "timelapse": {"label": "Fast clouds", "tech": "timelapse"},
                              "slowmo": {"label": "Slow-motion action"}}},
        "lighting": {"label": "Lighting", "desc": "Time of day and the mood of the light.",
                     "opts": {"auto": {"label": "Automatic"},
                              "golden": {"label": "Sunset glow", "tech": "golden hour", "desc": "Warm, soft, flattering."},
                              "blue_hour": {"label": "Dusk blue", "tech": "blue hour", "desc": "Cool calm light just after sunset."},
                              "night": {"label": "Night city"}, "neon": {"label": "Neon signs"},
                              "studio": {"label": "Soft studio", "desc": "Even, clean, flattering."},
                              "harsh": {"label": "Bright noon sun", "desc": "Strong shadows, high contrast."},
                              "candle": {"label": "Candlelight", "desc": "Warm, flickering, intimate."},
                              "backlit": {"label": "Light from behind", "tech": "rim light", "desc": "Glowing outline around the subject."},
                              "moody": {"label": "Dark & moody", "tech": "low-key", "desc": "Mostly shadow, dramatic."},
                              "overcast": {"label": "Cloudy day", "desc": "Soft, shadowless light."}}},
        "style": {"label": "Signature effect", "tech": "H3 style embedding",
                  "desc": "A trained special-effect move built into H3.",
                  "opts": {"none": {"label": "None"},
                           "art_is_explosion": {"label": "Paint explosion", "desc": "The scene bursts into colourful paint."},
                           "blooming_flowers": {"label": "Flowers bloom", "desc": "Flowers grow and open across the frame."},
                           "bullet_time": {"label": "Frozen-time spin", "tech": "bullet time", "desc": "Time stops while the camera sweeps around."},
                           "dark_magic": {"label": "Dark magic", "desc": "Swirling shadowy energy."},
                           "fire_breath": {"label": "Fire breath", "desc": "A burst of flame."},
                           "four_seasons": {"label": "Four seasons", "desc": "Spring to winter passes in one shot."},
                           "kiss_camera": {"label": "Kiss the lens", "desc": "Subject leans in to kiss the camera."},
                           "spiral_ascent": {"label": "Spiral up", "desc": "Camera spirals upward around the subject."},
                           "storm_magic": {"label": "Storm magic", "desc": "Lightning and wind summoned around the subject."},
                           "truman_show": {"label": "It's a set!", "tech": "Truman Show", "desc": "Pulls back to reveal it was a stage."}}},
        "fx_text": {"label": "Anything else in the scene", "desc": "Extra details in your own words."},
        # post effects
        "grade": {"label": "Colour filter", "tech": "colour grade", "desc": "Changes the colours after rendering, like an Instagram filter.",
                  "opts": {"none": {"label": "None"}, "warm": {"label": "Warm", "desc": "Golden, cosy."},
                           "cool": {"label": "Cool", "desc": "Blue, calm, wintry."},
                           "teal_orange": {"label": "Blockbuster", "tech": "teal & orange", "desc": "Orange skin, teal shadows — movie poster look."},
                           "bw": {"label": "Black & white"}, "vintage": {"label": "Faded vintage", "desc": "Washed-out old photo."},
                           "vivid": {"label": "Vivid", "desc": "Punchier colour."}, "contrast": {"label": "High contrast", "desc": "Deeper darks, brighter lights."}}},
        "grain": {"label": "Film grain", "desc": "Fine noise that gives a filmic texture.",
                  "opts": {"off": {"label": "Off"}, "light": {"label": "Light"}, "heavy": {"label": "Heavy"}}},
        "vignette": {"label": "Dark corners", "tech": "vignette", "desc": "Darkens the edges to pull the eye to the centre.",
                     "opts": {"off": {"label": "Off"}, "on": {"label": "On"}}},
        "sharpen": {"label": "Sharpen", "desc": "Crisper edges. Strong can look artificial.",
                    "opts": {"off": {"label": "Off"}, "light": {"label": "Light"}, "strong": {"label": "Strong"}}},
        "fade": {"label": "Fade", "desc": "Fade from/to black at the start or end.",
                 "opts": {"none": {"label": "None"}, "in": {"label": "Fade in"}, "out": {"label": "Fade out"}, "both": {"label": "Both"}}},
        "fps": {"label": "Smoothness", "tech": "frame rate", "desc": "More frames per second = smoother motion (extra frames are created).",
                "opts": {"24": {"label": "Cinematic", "tech": "24 fps", "desc": "Natural film look."},
                         "30": {"label": "Standard video", "tech": "30 fps"},
                         "48": {"label": "Smooth", "tech": "48 fps interpolated"},
                         "60": {"label": "Ultra smooth", "tech": "60 fps interpolated", "desc": "Sports / gaming look."}}},
        "upscale": {"label": "Enlarge", "tech": "upscale", "desc": "Makes the final video bigger in pixels.",
                    "opts": {"off": {"label": "Off"}, "1.5": {"label": "1.5× bigger"}, "2": {"label": "2× bigger"}}},
        "loop": {"label": "Loop", "desc": "Plays forward then backward for a seamless loop.",
                 "opts": {"off": {"label": "Off"}, "boomerang": {"label": "Boomerang"}}},
        # audio
        "audio": {"label": "Sound", "tech": "native audio", "desc": "H3 makes sound with the picture — effects, ambience, music.",
                  "opts": {"auto": {"label": "Automatic", "desc": "Fitting sound effects and music."},
                           "off": {"label": "Silent"}, "custom": {"label": "Describe it", "desc": "Use the text box below."}}},
        "audio_text": {"label": "Describe the sound", "desc": "e.g. waves, seagulls, soft piano."},
        "soundtrack": {"label": "Your attached audio", "desc": "What to do with an audio file you attached.",
                       "opts": {"replace": {"label": "Use it instead"}, "mix": {"label": "Blend with H3's sound"}, "ignore": {"label": "Ignore it"}}},
        "track_vol": {"label": "Attached audio volume", "desc": "1 = as is, 0 = silent, 2 = twice as loud (when blending)."},
        # references
        "ref_role": {"label": "What to copy from your pictures", "desc": "Which part of the reference pictures H3 should keep.",
                     "opts": {"identity": {"label": "The person or product", "desc": "Keeps faces and products recognisable."},
                              "style": {"label": "The look", "desc": "Copies colours and art style only."},
                              "scene": {"label": "The place", "desc": "Uses the location / background."},
                              "all": {"label": "Everything", "desc": "Person, outfit and place together."}}},
        "ref_size": {"label": "Reference detail", "tech": "reference size", "advanced": True,
                     "desc": "Max reads references at full detail; Match uses the video size.",
                     "opts": {"max": {"label": "Full detail"}, "match": {"label": "Match video size"}}},
        "ref_secs": {"label": "Reference clip length", "advanced": True, "desc": "How many seconds of a reference video to study."},
        # engine
        "enhance": {"label": "MUSE writes the prompt", "tech": "prompt director", "group": "Basics",
                    "desc": "On: MUSE expands your idea into a full shot plan. Off: your exact words.",
                    "opts": {"on": {"label": "On (recommended)"}, "off": {"label": "Off — my exact words", "tech": "--raw"}}},
        "lora_strength": {"label": "Turbo strength", "tech": "turbo LoRA strength", "advanced": True,
                          "desc": "How strongly the speed-up add-on is applied. Keep at 1."},
        "shift_video": {"label": "Motion vs detail balance", "tech": "sigma shift (video)", "advanced": True,
                        "desc": "Higher favours big motion, lower favours fine detail. Blank = default."},
        "shift_audio": {"label": "Sound balance", "tech": "sigma shift (audio)", "advanced": True,
                        "desc": "Same idea for the soundtrack. Blank = default."},
        "trim": {"label": "Cut frames off the start", "tech": "trim", "advanced": True,
                 "desc": "Drops the first few frames (fixes a jumpy first moment)."},
    },
    "music3": {
        "duration": {"label": "Song length", "desc": "Longest the song may run, in seconds (up to 5 minutes)."},
        "lyrics": {"label": "Lyrics", "desc": "Let MUSE write lyrics, or make it instrumental.",
                   "opts": {"auto": {"label": "MUSE writes them"}, "instrumental": {"label": "No vocals"}}},
        "cfg": {"label": "Sound strictness", "tech": "diffusion CFG"},
        "lm_cfg": {"label": "Song-plan strictness", "tech": "composer CFG", "advanced": True,
                   "desc": "How closely the song structure follows your description."},
        "top_k": {"label": "Composer variety", "tech": "top-k", "advanced": True,
                  "desc": "Higher = more surprising musical choices."},
        "model": {"label": "Model precision", "tech": "DiT precision", "advanced": True,
                  "desc": "Best quality, or lighter on memory.",
                  "opts": {"fp16": {"label": "Best", "tech": "fp16"}, "int8": {"label": "Lighter", "tech": "int8"}}},
        "decode": {"label": "Memory saver", "tech": "decode", "advanced": True, "desc": "Tiled uses less graphics memory.",
                   "opts": {"tiled": {"label": "Save memory", "tech": "tiled"}, "full": {"label": "Full", "tech": "full decode"}}},
        "seed": {"advanced": False},
    },
    "qimg": {
        "mode": {"label": "What to do", "tech": "mode", "desc": "Create a new picture, edit yours, or cut out the background.",
                 "opts": {"auto": {"label": "Automatic", "desc": "Edits if you attached pictures, else creates."},
                          "generate": {"label": "Create from words", "tech": "text → image"},
                          "edit": {"label": "Edit my pictures", "desc": "Change or combine the attached pictures."},
                          "cutout": {"label": "Remove background"}}},
        "aspect": {"label": "Shape", "tech": "aspect ratio", "desc": "Wide, tall or square.",
                   "opts": {"auto": {"label": "Automatic", "desc": "MUSE picks from your idea."}}},
        "size": {"label": "Size", "tech": "megapixels", "desc": "Bigger is sharper but slower.",
                 "opts": {"standard": {"label": "Standard", "tech": "~1 MP"}, "hd": {"label": "HD", "tech": "~2 MP"},
                          "max": {"label": "Maximum", "tech": "~4 MP", "desc": "Slow."}}},
        "cfg": {"desc": "Above 1 the 'Avoid' box starts working. Qwen likes low values (1–4)."},
        "enhance": {"label": "Expand my prompt", "tech": "prompt rewriter",
                    "desc": "On: rewrites your idea into the detailed description Qwen likes.",
                    "opts": {"on": {"label": "On (recommended)"}, "off": {"label": "Off — my exact words", "tech": "--raw"}}},
        "edit_res": {"label": "Edit detail", "tech": "reference resolution", "advanced": True,
                     "desc": "How closely attached pictures are studied. Auto adjusts to how many you add."},
        "cache": {"label": "Speed cache", "tech": "feature cache", "advanced": True,
                  "desc": "Reuses work between passes to go faster. Keep on auto."},
        "negative": {"label": "Avoid", "tech": "negative prompt",
                     "desc": "Things you don't want (e.g. blurry, text). Needs strictness above 1."},
        "seed": {"advanced": False},
        "upscale": {"label": "Enlarge", "tech": "upscale", "desc": "Makes the final picture bigger in pixels.",
                    "opts": {"off": {"label": "Off"}, "1.5": {"label": "1.5× bigger"}, "2": {"label": "2× bigger"}}},
    },
    "ace": {
        "mode": {"label": "What to make", "tech": "mode", "desc": "A new track, or a new take on audio you attached.",
                 "opts": {"auto": {"label": "Automatic", "desc": "Remixes if you attached audio, else creates."},
                          "text": {"label": "New track from words"},
                          "remix": {"label": "Remix my track", "desc": "Same song, new style."},
                          "cover": {"label": "Cover version", "desc": "Re-performs it, keeping its sound character."},
                          "voice": {"label": "Swap the singer", "desc": "Audio 1 = song, audio 2 = the new voice."}}},
        "duration": {"label": "Track length", "desc": "Seconds, for new tracks."},
        "shift": {"label": "Structure vs detail", "tech": "shift", "advanced": True,
                  "desc": "Higher favours overall shape, lower favours fine detail."},
        "cfg": {"label": "Sound strictness", "tech": "diffusion CFG"},
        "lm_cfg": {"label": "Song-plan strictness", "tech": "LM CFG", "advanced": True,
                   "desc": "How closely the song plan follows your description."},
        "temperature": {"label": "Adventurousness", "tech": "LM temperature", "advanced": True,
                        "desc": "Higher = wilder ideas, lower = safer."},
        "top_p": {"label": "Idea range", "tech": "top-p", "advanced": True, "desc": "Lower keeps to the most likely ideas."},
        "top_k": {"label": "Idea limit", "tech": "top-k", "advanced": True, "desc": "0 = no limit."},
        "min_p": {"label": "Idea floor", "tech": "min-p", "advanced": True, "desc": "Drops very unlikely ideas. 0 = off."},
        "codes": {"label": "Song planner", "tech": "audio-code LM", "advanced": True,
                  "desc": "A planning step that sketches the song first.",
                  "opts": {"auto": {"label": "Automatic", "desc": "Only for new tracks."}, "on": {"label": "Always"}, "off": {"label": "Never"}}},
        "bpm": {"label": "Tempo", "tech": "BPM", "desc": "Beats per minute. 70 = slow, 120 = dance, 170 = fast. Blank = auto."},
        "key": {"label": "Musical key", "desc": "Major sounds bright, minor sounds sad or dark.",
                "opts": {"auto": {"label": "Automatic"}}},
        "timesig": {"label": "Beat pattern", "tech": "time signature", "desc": "How beats are counted.",
                    "opts": {"4": {"label": "Standard", "tech": "4/4", "desc": "Most pop, rock, hip-hop."},
                             "3": {"label": "Waltz", "tech": "3/4"}, "6": {"label": "Swaying", "tech": "6/8", "desc": "Ballads, folk."},
                             "2": {"label": "March", "tech": "2/4"}}},
        "language": {"label": "Lyrics language", "desc": "The language the lyrics are sung in."},
        "remix": {"label": "How much to change (remix)", "tech": "remix strength", "desc": "Low = close to the original, high = new."},
        "cover": {"label": "How much to change (cover)", "tech": "cover strength", "desc": "Low = close to the original, high = new."},
        "voice": {"label": "How much of the new voice", "tech": "voice-swap strength", "desc": "Higher = more like the new singer."},
        "seed": {"advanced": False},
    },
    "llama": {
        "mode": {"label": "Writing style", "desc": "Clear and concise, or vivid and creative.",
                 "opts": {"chat": {"label": "Clear answers"}, "creative": {"label": "Creative writing"}}},
        "length": {"label": "Reply length", "desc": "How long MUSE's answers are.",
                   "opts": {"short": {"label": "Short"}, "medium": {"label": "Medium"}, "long": {"label": "Long"}}},
        "temperature": {"label": "Creativity", "tech": "temperature", "advanced": False, "group": "Basics",
                        "desc": "Low = focused and factual, high = imaginative."},
        "memory": {"label": "Remembers last", "tech": "turns", "desc": "How many earlier messages MUSE keeps in mind."},
        "seed": {"advanced": True},
    },
}

# ── a "what it does" line for every option that had none (Oct 9 2026). Merged under DOCS by _doc(); a DOCS desc wins ──
_KEYS = ["C", "C#", "D", "Eb", "E", "F", "F#", "G", "Ab", "A", "Bb", "B"]
_LANGS = {"en": "English", "es": "Spanish", "fr": "French", "de": "German", "it": "Italian", "pt": "Portuguese",
          "ja": "Japanese", "ko": "Korean", "zh": "Chinese", "ru": "Russian", "ar": "Arabic", "hi": "Hindi", "nl": "Dutch",
          "sv": "Swedish", "pl": "Polish", "tr": "Turkish"}
_ASPECT = {"1:1": "Square — feeds and profile posts.", "3:2": "Classic photo landscape.", "2:3": "Classic photo portrait.",
           "16:9": "Widescreen — TV, YouTube, laptops.", "9:16": "Tall — phones, Shorts, Reels, TikTok.",
           "4:3": "Old-TV / tablet shape.", "3:4": "Portrait tablet shape — good for full-body characters.",
           "4:5": "Tall feed post (Instagram portrait).", "5:4": "Nearly square landscape.",
           "21:9": "Extra-wide cinema strip.", "2:1": "Wide banner.", "1:2": "Tall banner / phone wallpaper."}
_UPSCALE = {"off": "Keep the rendered size.", "1.5": "50% bigger — a quick sharp resize after rendering.",
            "2": "Double the size — a quick sharp resize after rendering (no new detail is invented)."}
_WF = {"builtin": "The lab's own tested pipeline — the safe choice."}
OPT_DESC = {
    "*": {"quality": {"V0": "Best quality, variable size.", "320k": "High quality, fixed size.",
                      "128k": "Smallest file — fine for previews and phones."},
          "upscale": _UPSCALE, "workflow": _WF},
    "h3": {
        "aspect": {"4:3": _ASPECT["4:3"], "3:4": _ASPECT["3:4"]},
        "extend_anchor": {"22": "The new part starts from the last ~1 s of motion — the smoothest continuation.",
                          "5": "Starts from the last few frames — follows on, with more freedom to change.",
                          "1": "Starts from the final still only — most freedom, may jump in motion."},
        "join": {"cut": "Joins the parts back-to-back with the overlap removed — no visible seam when it works.",
                 "xfade": "Blends the parts over a quarter second — hides a seam at the cost of a soft moment."},
        "shot": {"auto": "Let the engine pick the framing from your words."},
        "motion": {"auto": "Let the engine decide how much moves."},
        "steady": {"on": "Keeps the camera smooth — no shake.", "off": "Allows handheld wobble and energetic moves."},
        "speed": {"0.75": "Slows the clip to three-quarter speed — dreamy.", "1": "Real time.",
                  "1.25": "A little faster — snappier.", "1.5": "Noticeably faster — comedic or energetic."},
        "look": {"auto": "No extra look — the engine follows your words."},
        "scene_fx": {"none": "No added effect.", "rain": "Falling rain and wet reflections.", "snow": "Gentle falling snow.",
                     "smoke": "Smoke drifting through the scene.", "sparks": "Glowing embers and sparks flying.",
                     "petals": "Flower petals drifting down.", "confetti": "A burst of party confetti.",
                     "lightning": "Storm with lightning flashes.", "particles": "Floating glowing magic dust.",
                     "bubbles": "Bubbles floating by.", "explosion": "An explosion with flying debris.",
                     "timelapse": "Clouds racing across the sky — time speeding up.",
                     "slowmo": "Action played in slow motion."},
        "lighting": {"auto": "No lighting instruction — follows your words.", "night": "Night-time with city lights.",
                     "neon": "Bright coloured neon signs and glow."},
        "style": {"none": "No extra effect."},
        "grade": {"none": "Colours as rendered.", "bw": "Black and white."},
        "grain": {"off": "Clean picture.", "light": "A little film grain — feels shot on film.",
                  "heavy": "Strong grain — old-film or gritty look."},
        "vignette": {"off": "Even brightness to the edges.", "on": "Darkens the corners to pull the eye to the centre."},
        "sharpen": {"off": "As rendered.", "light": "Slightly crisper edges.", "strong": "Very crisp — can look harsh."},
        "fade": {"none": "Starts and ends on picture.", "in": "Fades up from black at the start.",
                 "out": "Fades to black at the end.", "both": "Fades in and out — good for standalone clips."},
        "fps": {"30": "30 frames a second — standard for web video.",
                "48": "48 frames — extra frames are blended in for very smooth motion."},
        "loop": {"off": "Plays once.", "boomerang": "Plays forward then backward — a seamless loop."},
        "audio": {"off": "No sound is generated."},
        "soundtrack": {"replace": "Your track replaces any sound the clip had.",
                       "mix": "Your track plays under the clip's own sound.", "ignore": "Your track is not used."},
        "ref_size": {"max": "Reference pictures are used at full size — best detail.",
                     "match": "Reference pictures are resized to the video size — lighter and faster."},
        "enhance": {"on": "The engine rewrites your idea into a full scene, shot and sound plan (it also looks at your pictures).",
                    "off": "Your words are used exactly as written."},
    },
    "qimg": {
        "mode": {"generate": "Make a new picture from your words.", "cutout": "Removes the background from your picture."},
        "aspect": _ASPECT,
        "size": {"standard": "About 1 megapixel — fast and sharp enough for most uses.",
                 "hd": "About 2 megapixels — finer detail, roughly twice as slow."},
        "enhance": {"on": "Your idea is rewritten into a detailed picture description first.",
                    "off": "Your words are used exactly as written."},
        "edit_res": {"auto": "Picks a working size from how many pictures you attach.",
                     "512": "Small — fastest, softer detail.", "768": "Medium — quick with decent detail.",
                     "1024": "Large — the usual choice for edits.", "1536": "Very large — most detail, slow and memory-hungry."},
        "cache": {"auto": "Lets the lab decide where to keep the model between jobs.",
                  "gpu": "Keeps the model on the graphics card — fastest repeat jobs, uses video memory.",
                  "cpu": "Parks the model in system memory — frees the graphics card, slower start.",
                  "off": "Unloads after every job — slowest, frees everything."},
    },
    "music3": {
        "lyrics": {"auto": "The engine writes lyrics that fit your idea.", "instrumental": "No vocals — music only."},
        "model": {"fp16": "Full-precision model — best sound.", "int8": "Compressed model — lighter on memory, very close in sound."},
        "decode": {"tiled": "Builds the audio in pieces — works on smaller graphics cards.",
                   "full": "Builds it in one go — a little faster if you have the memory."},
    },
    "ace": {
        "mode": {"text": "Make a new song from your description."},
        "codes": {"on": "Plans the song's structure first — more coherent songs.", "off": "Skips the planning step — faster, looser."},
        "key": dict({"auto": "Let the engine choose the key."},
                    **{"%s major" % k: "%s major — bright and happy." % k for k in _KEYS},
                    **{"%s minor" % k: "%s minor — darker, more emotional." % k for k in _KEYS}),
        "timesig": {"4": "4/4 — most pop, rock and dance songs.", "3": "3/4 — a waltz feel.",
                    "2": "2/4 — a march / polka feel.", "6": "6/8 — a rolling, swinging feel."},
        "language": dict({"unknown": "Let the engine detect it from the lyrics."},
                         **{k: "Sung in %s." % v for k, v in _LANGS.items()}),
    },
    "llama": {
        "mode": {"chat": "Clear, direct answers.", "creative": "Vivid, original writing — stories, lyrics, ideas."},
        "length": {"short": "About 300 words.", "medium": "About 800 words.", "long": "About 2000 words."},
    },
}

ADVANCED = "Advanced (leave as is)"
_manifest = {"mtime": None, "data": {}}


def manifest():
    """{"h3/camera/dolly_in": {"poster": "fx/h3/camera/dolly_in.jpg", "video": "fx/…mp4"}} — reloaded on change."""
    path = os.path.join(FX_DIR, "manifest.json")
    try:
        mt = os.path.getmtime(path)
        if mt != _manifest["mtime"]:
            with open(path, encoding="utf-8") as f:
                _manifest.update(mtime=mt, data=json.load(f))
    except OSError:                                 # compiled build: static/ is embedded in the binary
        if _manifest["mtime"] != "asset":
            try:
                import core
                raw = core.asset("fx/manifest.json")
                _manifest.update(mtime="asset", data=json.loads(raw) if raw else {})
            except Exception:
                _manifest.update(mtime="asset", data={})
    except ValueError:
        _manifest.update(mtime=None, data={})
    return _manifest["data"]


def _doc(model, k):
    base, own = COMMON.get(k) or {}, DOCS.get(model, {}).get(k) or {}
    d = dict(base, **{x: y for x, y in own.items() if x != "opts"})
    d["opts"] = dict(base.get("opts") or {})
    for v, od in (own.get("opts") or {}).items():
        d["opts"][v] = dict(d["opts"].get(v) or {}, **od)
    for src in (OPT_DESC["*"].get(k) or {}, OPT_DESC.get(model, {}).get(k) or {}):
        for v, txt in src.items():
            if not (d["opts"].get(v) or {}).get("desc"):
                d["opts"][v] = dict(d["opts"].get(v) or {}, desc=txt)
    return d


def apply(model, field):
    """A copy of the field with docs + previews merged in. Original label is kept as `tech` when renamed."""
    d = _doc(model, field["k"])
    if not d.get("desc") and not d.get("label") and not d.get("opts") and "advanced" not in d:
        return field
    f = dict(field)
    if d.get("label") and d["label"] != f.get("label"):
        f["tech"] = d.get("tech") or f.get("label")
        f["label"] = d["label"]
    elif d.get("tech"):
        f["tech"] = d["tech"]
    if d.get("desc"):
        f["desc"] = d["desc"]
    if d.get("group"):
        f["group"] = d["group"]
    if d.get("advanced"):
        f["advanced"] = True
        f["group"] = ADVANCED       # old apps also show it in its own (last) group
    man = manifest()
    if f.get("type") == "select":
        opts, odesc, oprev = [], {}, {}
        for o in f.get("opts") or []:
            v, lab = (o[0], o[1]) if isinstance(o, list) else (o, o)
            od = d["opts"].get(str(v)) or {}
            tech = od.get("tech") or (lab if od.get("label") and od["label"] != lab else "")
            if od.get("label"):
                lab = od["label"] + (" · " + tech if tech else "")
            opts.append([v, lab])
            if od.get("desc"):
                odesc[str(v)] = od["desc"]
            p = man.get("%s/%s/%s" % (model, f["k"], v))
            if p:
                oprev[str(v)] = p
        f["opts"] = opts
        if odesc:
            f["odesc"] = odesc
        if oprev:
            f["opreview"] = oprev
    return f
