"""SERIES help — a plain one-line "what it does" for every Setup / song / character-builder / object-builder field and
option. Data only, merged into series_presets.catalog() as "help"; the page shows the field line under its label and the
picked (or hovered) option's line under its chips. Identical in the MirOS copy (miros_mlab) — copy, never import across.

HELP[field] = {"desc": field line, "opts": {option: option line}}. Option values are the exact preset strings.
"""

HELP = {
    # ── Setup ─────────────────────────────────────────────────────────────────────────────────────────────────────────
    "struct": {"desc": "How an episode is built: the order of beats and which ones are sung, spoken or just music."},
    "style": {"desc": "The look every picture and shot of the series uses. You can still fine-tune it on the Style tab."},
    "len": {"desc": "How long one finished episode is. Longer = more shots and more render time.",
            "opts": {"30": "A teaser or short — about 3 shots.", "60": "One verse and chorus — about 6 shots.",
                     "90": "A short song with a dance break.", "120": "A full kids' song — the usual episode length.",
                     "150": "A song with an extra verse.", "180": "A long episode — the longest render."}},
    "aspect": {"desc": "The shape of the picture — pick where the episode will be watched.",
               "opts": {"16:9": "Widescreen — TV, YouTube, laptops.", "9:16": "Tall — phones, Shorts, Reels, TikTok.",
                        "1:1": "Square — feeds and posts.", "21:9": "Extra-wide cinema strip (letterbox on TVs)."}},
    "clip": {"desc": "Roughly how long each generated shot is. The song is cut into shots of about this length.",
             "opts": {"6": "Quick cuts — lively, more shots to render.", "8": "Snappy — good for fast songs.",
                      "10": "One musical phrase per shot — the balanced default.",
                      "12": "Long, calm shots — fewer renders, slower pace."}},
    "res": {"desc": "How sharp the shots are rendered. Higher is clearer and much slower.",
            "opts": {"draft": "Fast low-res test — check the story and timing before a real render.",
                     "standard": "Good quality, about 3–5 minutes per shot — the best balance.",
                     "high": "Sharper detail, roughly twice as slow.",
                     "max": "Sharpest (768p), very slow — for the final version only."}},
    "join": {"desc": "What happens where one shot ends and a new one starts (‘continue’ shots always join seamlessly).",
             "opts": {"soft": "A short dissolve blends the two shots — smooth and gentle.",
                      "cut": "A clean instant cut — punchy, like TV editing."}},
    # ── Song ──────────────────────────────────────────────────────────────────────────────────────────────────────────
    "genre": {"desc": "The kind of music — sets the instruments and the groove.",
              "opts": {"nursery rhyme": "Ukulele, glockenspiel and hand claps — classic and bouncy.",
                       "bubblegum pop": "Bright synths, punchy drums and a very catchy hook.",
                       "rock": "Friendly guitars, live drums and a big shout-along chorus.",
                       "lullaby": "Music box, soft piano and strings — slow and calm.",
                       "reggae": "Sunny off-beat guitar and steel drums — relaxed groove.",
                       "kids hip-hop": "A playful boom-bap beat with call-and-response.",
                       "marching band": "Brass, snare rolls and a stomping beat.",
                       "Latin pop": "Congas, maracas and nylon guitar — made for dancing.",
                       "country": "Banjo, fiddle and a foot-stomp beat.",
                       "disco": "Four-on-the-floor beat, funky bass and strings.",
                       "Broadway show tune": "Full orchestra and a big theatrical finish.",
                       "electronic dance": "Bouncy synth bass, sparkling arps and a drop on the chorus."}},
    "bpm": {"desc": "Song speed in beats per minute. 60–80 is slow and calm, 100 is a walk, 130+ is a dance."},
    "mood": {"desc": "The feeling of the song — changes the melody and how it is sung.",
             "opts": {"happy": "Bright and smiley.", "silly": "Goofy, playful, with funny sounds.",
                      "brave": "Bold and heroic — a ‘we can do it’ song.", "calm": "Soft and soothing.",
                      "dreamy": "Floaty and magical.", "triumphant": "A big victorious finish."}},
    "vocal": {"desc": "Who sings — sets the voices the song is written for and who lip-syncs each shot.",
              "opts": {"solo lead": "One character sings the whole song.",
                       "duet": "Two characters take turns and sing together.",
                       "call and response": "One sings a line, the others answer it back.",
                       "kids choir": "A group of kids sings together.",
                       "whole cast": "Everyone joins in — lines are shared around the cast."}},
    "lang": {"desc": "The language the lyrics are written and sung in.",
             "opts": {"English": "Sung in English.", "Spanish": "Sung in Spanish.", "French": "Sung in French.",
                      "Portuguese": "Sung in Portuguese.",
                      "bilingual EN/ES": "Mixes English and Spanish lines — great for learning songs."}},
    # ── Character builder ─────────────────────────────────────────────────────────────────────────────────────────────
    "kind": {"desc": "What the character is — a person, an animal, a creature or a talking thing.",
             "opts": {"kid": "A school-age child.", "toddler": "A tiny child, 2–3 years old.",
                      "grown-up": "An adult — a parent, teacher or helper.", "grandparent": "A grandma or grandpa.",
                      "bunny": "A rabbit with long ears.", "bear cub": "A fluffy young bear.", "fox": "A clever little fox.",
                      "puppy": "A young dog.", "kitten": "A young cat.", "duck": "A duck with a beak and webbed feet.",
                      "elephant": "A little elephant with a trunk.", "lion cub": "A young lion.",
                      "crocodile": "A friendly crocodile.", "dinosaur": "A cartoon dinosaur.", "penguin": "A waddling penguin.",
                      "owl": "A wise owl.", "monkey": "A cheeky monkey.", "unicorn": "A magical horse with a horn.",
                      "dragon": "A friendly little dragon.", "robot": "A metal or plastic robot.",
                      "alien": "A visitor from another planet.", "monster": "A cute, not-scary monster.",
                      "fairy": "A tiny winged fairy.", "talking toy": "A toy that has come to life.",
                      "talking fruit": "A piece of fruit with a face.", "talking car": "A car with a face and a voice."}},
    "gender": {"desc": "Shapes the character's look and name ideas. ‘Any’ lets the drawing decide.",
               "opts": {"any": "Let the drawing decide.", "boy": "Drawn as a boy.", "girl": "Drawn as a girl.",
                        "neither": "No boy/girl cues — good for robots, monsters and creatures."}},
    "age": {"desc": "How old they look (people only). Animals and creatures just read as young or grown."},
    "role": {"desc": "Their job in the story — the writers use it to give them lines and moments.",
             "opts": {"lead": "The main character — the story follows them.",
                      "best friend": "Always by the lead's side.", "sidekick": "A helper who tags along and gets the jokes.",
                      "mentor": "The wise one who teaches the lesson.", "comic relief": "Here to make everyone laugh.",
                      "little sibling": "The small one who copies everyone.",
                      "grumpy-but-kind": "Grumbles a lot, cares a lot.", "narrator": "Tells the story to the viewer."}},
    "height": {"desc": "How tall they stand next to the others — used for the lineup so sizes stay consistent."},
    "build": {"desc": "The overall body shape — the silhouette viewers recognise from far away.",
              "opts": {"round and chubby": "Soft and round all over.", "small and slim": "Little and slender.",
                       "tall and lanky": "Long arms and legs.", "sturdy and strong": "Solid and broad.",
                       "pear-shaped": "Narrow on top, wide at the bottom.", "bean-shaped": "One smooth rounded body."}},
    "head": {"desc": "Head size compared with the body. Bigger heads read as younger and cuter.",
             "opts": {"normal": "Natural proportions.", "big": "A cartoon-big head.",
                      "very big (chibi)": "A huge head on a tiny body — super cute."}},
    "skin": {"desc": "Skin, fur or body colour."},
    "accent": {"desc": "The character's signature colour — used for their outfit so they are easy to spot in every shot."},
    "eyes": {"desc": "Eye shape — the biggest part of a character's expression.",
             "opts": {"big round": "Large round eyes — friendly and readable.", "sparkly": "Shiny highlights — excited and magical.",
                      "sleepy half-closed": "Droopy lids — relaxed or dozy.", "button dots": "Simple dots — classic cartoon.",
                      "almond": "Narrower, natural shape.", "with glasses": "Wears a pair of glasses.",
                      "one big eye": "A single large eye — for robots and monsters."}},
    "eyecolor": {"desc": "The colour of the eyes.",
                 "opts": {"brown": "Brown eyes.", "blue": "Blue eyes.", "green": "Green eyes.", "hazel": "Hazel (green-brown) eyes.",
                          "black": "Dark black eyes.", "violet": "Fantasy violet eyes."}},
    "face": {"desc": "Little extras that make a face memorable. Pick as many as you like.",
             "opts": {"freckles": "Freckles across the nose and cheeks.", "rosy cheeks": "Pink blushing cheeks.",
                      "gap tooth": "A gap between the front teeth.", "dimples": "Dimples when they smile.",
                      "bushy eyebrows": "Big expressive eyebrows.", "whiskers": "Animal whiskers.",
                      "a little beak": "A small beak instead of a nose.", "big ears": "Large ears that stick out."}},
    "hair": {"desc": "The hairstyle (or fur tuft). A strong hair shape is easy to recognise.",
             "opts": {"none": "No hair — bald, or animals with fur only.", "short spiky": "Short spikes pointing up.",
                      "curly afro": "A big round curly afro.", "two pigtails": "Two bunches, one each side.",
                      "long straight": "Long straight hair.", "ponytail": "Hair tied back in one tail.",
                      "bob cut": "A chin-length bob.", "messy mop": "Shaggy, untidy hair.", "braids": "Plaited braids.",
                      "top bun": "A bun on top of the head.", "mohawk": "A strip of hair down the middle.",
                      "fluffy tuft": "A small fluffy tuft on top."}},
    "haircolor": {"desc": "The colour of the hair.",
                  "opts": {"black": "Black hair.", "brown": "Brown hair.", "blonde": "Blonde hair.", "ginger": "Ginger / red hair.",
                           "white": "White hair.", "pink": "Fun pink hair.", "blue": "Fun blue hair.", "green": "Fun green hair.",
                           "purple": "Fun purple hair."}},
    "top": {"desc": "What they wear on top. It is coloured with the signature colour.",
            "opts": {"t-shirt": "A simple t-shirt.", "hoodie": "A cosy hooded top.", "striped jumper": "A striped sweater.",
                     "dungarees": "Bib overalls with straps.", "raincoat": "A shiny raincoat.", "dress": "A dress.",
                     "overalls": "Work overalls.", "lab coat": "A white scientist's coat.", "superhero cape": "A flowing cape.",
                     "sports jersey": "A team shirt with a number.", "pyjamas": "Bedtime pyjamas.", "none": "Nothing on top."}},
    "bottom": {"desc": "What they wear on their legs.",
               "opts": {"shorts": "Shorts.", "jeans": "Blue jeans.", "skirt": "A skirt.", "leggings": "Stretchy leggings.",
                        "trousers": "Long trousers.", "tutu": "A puffy ballet tutu.", "none": "Nothing — fine for animals."}},
    "shoes": {"desc": "What they wear on their feet.",
              "opts": {"sneakers": "Trainers.", "rain boots": "Wellies for puddles.", "sandals": "Open sandals.",
                       "light-up shoes": "Shoes with glowing soles.", "slippers": "Fluffy slippers.", "barefoot": "No shoes."}},
    "accessory": {"desc": "Extra things they always wear. Pick as many as you like.",
                  "opts": {"backpack": "A backpack.", "cap": "A baseball cap.", "bow": "A hair bow.", "scarf": "A scarf.",
                           "crown": "A little crown.", "headphones": "Headphones round the neck or on.", "bandana": "A bandana.",
                           "star badge": "A shiny star badge.", "watch": "A wristwatch.", "flower": "A flower in the hair."}},
    "item": {"desc": "The one thing they always carry — it shows up in their shots and the story.",
             "opts": {"none": "Nothing in their hands.", "ukulele": "A little ukulele.", "microphone": "A microphone to sing into.",
                      "magnifying glass": "For investigating.", "toy rocket": "A toy rocket.", "paintbrush": "A paintbrush.",
                      "teddy": "A teddy bear.", "ball": "A ball.", "magic wand": "A sparkly wand.", "book": "A favourite book."}},
    "traits": {"desc": "Personality — shapes their poses, expressions and the lines the writer gives them.",
               "opts": {"curious": "Always asking why.", "brave": "First to try something new.", "shy": "Quiet, hides a little.",
                        "silly": "Loves jokes and funny faces.", "kind": "Helps everyone.", "bossy": "Likes to be in charge.",
                        "dreamy": "Head in the clouds.", "energetic": "Never stops moving.", "clumsy": "Trips and spills (funny).",
                        "clever": "Solves the problem.", "cheeky": "A little mischievous.", "gentle": "Soft and calm."}},
    "move": {"desc": "How they move in the videos — their walk, dance and body language.",
             "opts": {"bouncy": "Springs up and down with every step.", "graceful": "Smooth, flowing movement.",
                      "waddling": "Side-to-side waddle.", "zooming": "Rushes everywhere fast.", "tiptoe": "Light, careful steps.",
                      "stomping": "Big heavy steps.", "wiggly dancer": "Can't stop wiggling to the music."}},
    "catch": {"desc": "A line they always say — the writers drop it into their dialogue and songs."},
    "range": {"desc": "Their singing voice — written into the song so the right voice sings their lines.",
              "opts": {"high and bright": "A light, high voice.", "sweet middle": "A sweet mid-range voice.",
                       "warm low": "A warm, lower voice.", "squeaky": "A tiny squeaky voice — great for small animals.",
                       "raspy": "A scratchy, gravelly voice.", "deep and booming": "A big deep voice."}},
    "tone": {"desc": "How they sound when they sing and talk.",
             "opts": {"cheerful": "Smiley and upbeat.", "gentle": "Soft and kind.", "excited": "Full of energy.",
                      "sleepy": "Slow and yawny.", "funny": "Goofy, comedic delivery.", "confident": "Strong and sure."}},
    "vaccent": {"desc": "Their accent when singing.",
                "opts": {"neutral": "No particular accent.", "American": "American accent.", "British": "British accent.",
                         "Irish": "Irish accent.", "Australian": "Australian accent.", "Spanish": "Spanish accent.",
                         "Southern": "American Southern accent."}},
    # ── Object builder ────────────────────────────────────────────────────────────────────────────────────────────────
    "o_kind": {"desc": "What the object is — a vehicle, an animal, a plant, a building or a prop."},
    "o_era": {"desc": "The design style or time period it comes from.",
              "opts": {"modern": "Today's design.", "vintage": "Old-fashioned and charming.",
                       "classic 1950s": "Rounded chrome-and-pastel fifties style.", "futuristic": "Sleek, from the future.",
                       "fantasy": "Magical, fairy-tale design.", "steampunk": "Brass, gears and pipes.",
                       "toy-like": "Looks like a chunky toy.", "storybook": "Like a picture-book illustration."}},
    "o_size": {"desc": "How big it is next to the cast — keeps its size the same in every shot."},
    "o_shape": {"desc": "Its overall shape and silhouette.",
                "opts": {"rounded and bubbly": "Soft rounded curves.", "sleek and streamlined": "Smooth and fast-looking.",
                         "boxy": "Square and blocky.", "chunky and sturdy": "Thick and solid.", "tall and thin": "Narrow and tall.",
                         "long and low": "Stretched out and low to the ground.", "squashy and soft": "Squishy like a cushion.",
                         "spiky": "Pointy edges.", "wobbly and hand-made": "Uneven, home-made charm."}},
    "o_color": {"desc": "Its main colour."},
    "o_accent": {"desc": "A second colour for trims and details."},
    "o_material": {"desc": "What it is made of — changes how it shines and feels.",
                   "opts": {"painted metal": "Smooth painted metal.", "chrome": "Mirror-shiny metal.", "wood": "Wooden.",
                            "plastic": "Glossy plastic.", "glass": "See-through glass.", "fabric": "Soft cloth.",
                            "stone": "Rough stone.", "fur": "Furry.", "feathers": "Feathered.", "scales": "Scaly skin.",
                            "leaves and bark": "Leaves and bark (plants).", "rubber": "Bouncy rubber.", "candy": "Made of sweets.",
                            "crystal": "Sparkling crystal.", "paper and cardboard": "Paper and cardboard craft.",
                            "knitted wool": "Knitted, cosy wool."}},
    "o_finish": {"desc": "Surface finish and patterns. Pick as many as you like.",
                 "opts": {"shiny": "Glossy reflections.", "matte": "No shine.", "glowing": "Gives off light.",
                          "sparkly": "Glitter and sparkles.", "rusty": "Rust patches.", "worn and old": "Scuffed and well used.",
                          "brand new": "Spotless.", "muddy": "Splashed with mud.", "stripes": "Striped pattern.",
                          "polka dots": "Spotty pattern.", "painted flames": "Hot-rod flames.", "stars": "Star pattern.",
                          "patchwork": "Patched pieces."}},
    "o_parts": {"desc": "Extra parts and details it has. Pick as many as you like.",
                "opts": {"big wheels": "Oversized wheels.", "whitewall tyres": "Classic white-sided tyres.", "wings": "Wings.",
                         "propeller": "A spinning propeller.", "headlights": "Front lights.", "round windows": "Porthole windows.",
                         "antenna": "An antenna.", "flag": "A little flag.", "chimney": "A chimney.", "sails": "Sails.",
                         "rocket boosters": "Rocket engines.", "a bell": "A bell.", "a long tail": "A long tail.", "horns": "Horns.",
                         "big paws": "Big paws.", "flowers": "Flowers on it.", "fruit": "Fruit growing on it.",
                         "a number on the side": "A racing number.", "a little door": "A small door.", "stickers": "Stickers.",
                         "a basket": "A basket.", "a roof rack": "A roof rack."}},
    "o_face": {"desc": "Whether it is a normal object or a living cartoon character with a face.",
               "opts": {"no face (a real object)": "A normal object — no face.", "cute eyes": "Just a pair of cute eyes.",
                        "full cartoon face": "Eyes, mouth and expressions — it can talk.",
                        "eyes in the headlights / windows": "Its lights or windows become its eyes (like cartoon cars)."}},
    "o_mood": {"desc": "The feeling it gives off.",
               "opts": {"friendly": "Warm and welcoming.", "cosy": "Snug and comfy.", "heroic": "Bold and brave.",
                        "magical": "Enchanted and glowing.", "silly": "Goofy and fun.", "spooky-cute": "A little spooky, still cute.",
                        "sleek and cool": "Stylish and fast.", "sleepy": "Droopy and relaxed."}},
    "o_move": {"desc": "How it moves in the videos.",
               "opts": {"stays still": "It doesn't move.", "rolls along": "Rolls on wheels.", "zooms": "Speeds past.",
                        "flies": "Flies through the air.", "floats": "Drifts gently.", "sails": "Sails on water.",
                        "hops": "Jumps along.", "gallops": "Runs on four legs.", "sways in the wind": "Rocks gently in the breeze.",
                        "spins": "Turns round and round.", "bounces": "Bounces up and down.",
                        "chugs and puffs": "Chugs along, puffing smoke like a train."}},
}

# objects whose kind needs no explanation still get a line
_OBJ_KINDS = {"car": "a car", "race car": "a racing car", "truck": "a truck", "fire engine": "a fire engine", "bus": "a bus",
              "tractor": "a farm tractor", "digger": "a digger", "motorbike": "a motorbike", "bicycle": "a bicycle",
              "train": "a train", "airplane": "an aeroplane", "helicopter": "a helicopter", "rocket": "a space rocket",
              "boat": "a boat", "pirate ship": "a pirate ship", "submarine": "a submarine", "hot-air balloon": "a hot-air balloon",
              "horse": "a horse", "dog": "a dog (a pet, not a cast member)", "cat": "a cat (a pet)", "bird": "a bird",
              "fish": "a fish", "butterfly": "a butterfly", "cow": "a cow", "sheep": "a sheep", "frog": "a frog",
              "tree": "a tree", "palm tree": "a palm tree", "flower": "a flower", "cactus": "a cactus", "mushroom": "a mushroom",
              "potted plant": "a plant in a pot", "vegetable patch": "a vegetable garden", "house": "a house",
              "castle": "a castle", "treehouse": "a treehouse", "tent": "a tent", "toy": "a toy", "ball": "a ball",
              "kite": "a kite", "teddy bear": "a teddy bear", "cake": "a cake", "fruit basket": "a basket of fruit",
              "lamp": "a lamp", "chair": "a chair", "bed": "a bed", "treasure chest": "a treasure chest",
              "magic wand": "a magic wand", "musical instrument": "a musical instrument", "gadget": "a gadget or machine"}
HELP["o_kind"]["opts"] = {k: "Makes %s that looks the same in every shot." % v for k, v in _OBJ_KINDS.items()}


def help_for(fields_by_key, colour):
    """HELP with the swatch fields filled with their colour names (the swatch itself is the preview)."""
    out = {k: {"desc": v.get("desc", ""), "opts": dict(v.get("opts") or {})} for k, v in HELP.items()}
    for k, f in fields_by_key.items():
        if f.get("type") == "swatch":
            h = out.setdefault(k, {"desc": "", "opts": {}})
            for o in f.get("opts") or []:
                h["opts"].setdefault(o, (colour(o) or o).capitalize() + ".")
    return out
